version: '3.9'

services:
  fact-check-server:
    container_name: fact-check-api
    image: fact-check-api
    build:
      context: .
      dockerfile: src/deployments/fact-check-server/Dockerfile
    ports:
      - "${SERVER_PORT}:8000"
    depends_on:
      - news-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  news-db:
    container_name: news-db
    image: news-db
    build:
      context: .
      dockerfile: src/deployments/news-db/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data