version: '3.9'

services:
  aletheia-api:
    container_name: aletheia-api
    image: aletheia-api
    build:
      context: .
      dockerfile: src/deployments/aletheia-api/Dockerfile
    ports:
      - "${SERVER_PORT}:8000"
      - "40000:40000"  # Delve remote debugging
    depends_on:
      - aletheia-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  aletheia-db:
    container_name: aletheia-db
    image: aletheia-db
    build:
      context: .
      dockerfile: src/deployments/aletheia-db/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data