CREATE TABLE languages (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE news_outlet (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    URL TEXT NOT NULL,
    LANGUAGE INT NOT NULL,
    CREDIBILITY INT NOT NULL
);

ALTER TABLE news_outlet
ADD CONSTRAINT fk_language
FOREIGN KEY (language) REFERENCES languages(id);