version: 2
updates:
  # Go (client/ and server-api/)
  - package-ecosystem: "gomod"
    directory: "/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/server-api"
    schedule:
      interval: "weekly"

  # Python (ai-analyzer/)
  - package-ecosystem: "pip"
    directory: "/ai-analyzer"
    schedule:
      interval: "weekly"
