name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
        module: [ 'server-api', 'client' ]  # Add all your module directories here

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Display Go version
        run: go version
      
      - name: Install dependencies for ${{ matrix.module }}
        working-directory: ./${{ matrix.module }}
        run: |
          go mod download
          go mod verify
      
      - name: Build ${{ matrix.module }}
        working-directory: ./${{ matrix.module }}
        run: go build -v ./...
      
      - name: Test ${{ matrix.module }}
        working-directory: ./${{ matrix.module }}
        run: go test -v ./...
